# Generated by Django 5.2.2 on 2025-06-07 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesperson', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
