# Generated by Django 5.2.2 on 2025-06-09 22:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salesperson", "0003_alter_sale_total_amount"),
    ]

    operations = [
        migrations.CreateModel(
            name="PDFAccessToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("is_used", models.BooleanField(default=False)),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pdf_tokens",
                        to="salesperson.sale",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["token"], name="salesperson_token_8064c0_idx"),
                    models.Index(
                        fields=["expires_at"], name="salesperson_expires_581f5d_idx"
                    ),
                ],
            },
        ),
    ]
